apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: tc6
  name: tc6
spec:
  finalizers:
  - kubernetes
---  
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-color
  name: webapp-color
  namespace: tc6
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    name: webapp-color
    ports:
     - containerPort: 8080
    env:
     - name: APP_COLOR
       value: red
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: webapp-color
  name: webapp-color
  namespace: tc6
spec:
  ports:
  - nodePort: 30491
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: webapp-color
  type: NodePort

