apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: tc8
  name: tc8
spec:
  finalizers:
  - kubernetes
---  
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod
  name: nginx-pod
  namespace: tc8
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: nginx:latest
    name: nginx
    ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-svc
  name: nginx-svc
  namespace: tc8
spec:
  ports:
  - nodePort: 30086
    port: 80 
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-pod
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-network-policy
  namespace: tc8
spec:
  podSelector:
    matchLabels:
      role: nginx-pod
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.96/24
    ports:
    - protocol: TCP
      port: 80