apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: tc9-front
  name: tc9-front
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: tc9-back
  name: tc9-back
spec:
  finalizers:
  - kubernetes

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vote-app-network-policy
  namespace: tc9-back
spec:
  podSelector:
    matchLabels:
      app: azure-vote-back
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tc9-front
      podSelector:
        matchLabels:
          app: azure-vote-front
    ports:
    - protocol: TCP
      port: 6800
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vote-app-network-policy
  namespace: tc9-front
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
  namespace: tc9-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
        namespace: tc9-back
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: azure-vote-back
        image: ronakgpatel/azure-voting-redis-db:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
  namespace: tc9-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  namespace: tc9-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: azure-vote-front
        namespace: tc9-front
    spec:
      imagePullSecrets:
      - name: regcred    
      containers:
      - name: azure-vote-front
        image: ronakgpatel/azure-voting-front:v1
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back.tc9-back.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  namespace: tc9-front
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
  selector:
    app: azure-vote-front