apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: tc9
  name: tc9
spec:
  finalizers:
  - kubernetes
---  
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vote-app-network-policy
  namespace: tc9
spec:
  podSelector:
    matchLabels:
      name: azure-vote-back
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tc9
    - podSelector:
        matchLabels:
          name: azure-vote-front
    ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
  namespace: tc9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
        namespace: tc9
    spec:
      containers:
      - name: azure-vote-back
        image: ronakgpatel/azure-voting-redis-db:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
  namespace: tc9
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  namespace: tc9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: azure-vote-front
        namespace: tc9
    spec:
      containers:
      - name: azure-vote-front
        image: ronakgpatel/azure-voting-front:v1
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  namespace: tc9
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
  selector:
    app: azure-vote-front