apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-color
  name: webapp-color
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    name: webapp-color
    ports:
     - containerPort: 8080
    env:
     - name: APP_COLOR
       value: red
