apiVersion: v1
kind: Service
metadata:
  labels:
    run: webapp-color
  name: webapp-color
spec:
  ports:
  - nodePort: 30491
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: webapp-color
  type: NodePort
